config_path: "DRUPAL_PROJECT_PATH"
config_file: "./nightwatch.conf.js"
features_path: "DRUPAL_PROJECT_PATH/tests/features"
html_report: true
html_report_dir: "DRUPAL_PROJECT_PATH/tests/reports"
html_report_format: "bootstrap"
json_report: false
json_report_dir: "DRUPAL_PROJECT_PATH/tests/reports"
log_report_dir: "DRUPAL_PROJECT_PATH/tests/logs"
editing_mode: "free_text"
